# # # This block iterates through all input variables defined in your Terraform configuration
# # # and exports them to a local YAML file.

# # resource "local_file" "all_variables_yaml" {

# #   filename = "${path.cwd}/terraform_variables.yaml"
# #   content = <<-EOT
# #     # Terraform Variables Exported on ${formatdate("YYYY-MM-DD hh:mm:ss ZZZ", timestamp())}
# #     # Generated by Terraform
# #     ---
# #     ${
# #   join("\n", [
# #     "DATALAKE_BKT: ${jsonencode(var.DATALAKE_BKT)}",
# #     "GLUE_ASSETS_BKT: ${jsonencode(var.GLUE_ASSETS_BKT)}", # Assuming this exists
# #     "TEMP_BKT: ${jsonencode(var.TEMP_BKT)}",               # Assuming this exists
# #     "LFN_ROLE_NAME: ${jsonencode(module.glue_event_based_pipeline.LFN_ROLE_NAME)}",
# #     # Add more variables as needed
# #   ])
# # }
# #   EOT

# # file_permission = "0644"
# # }



# # Collect all variables into a single locals map
# locals {
#   all_vars = {
#     DATALAKE_BKT           = var.BUCKETS[0]
#     GLUE_ASSETS_BKT        = var.BUCKETS[1]
#     TEMP_BKT               = var.BUCKETS[2]
#     LFN_ROLE_NAME          = module.glue_event_based_pipeline.LFN_ROLE_NAME
#     LFN_ROLE_ARN           = module.glue_event_based_pipeline.LFN_ROLE_ARN
#     GLUE_ROLE_NAME         = module.glue_event_based_pipeline.GLUE_ROLE_NAME
#     GLUE_ROLE_ARN          = module.glue_event_based_pipeline.GLUE_ROLE_ARN
#     GLUE_CATALOG_DB_BRONZE = var.GLUE_CATALOG_DB_NAMES[0]
#     GLUE_CATALOG_DB_SILVER = var.GLUE_CATALOG_DB_NAMES[1]
#     GLUE_CATALOG_DB_GOLD   = var.GLUE_CATALOG_DB_NAMES[2]

#     ###############################################################################
#     ######### Redshift Analysis Module Variables
#     ###############################################################################

#     # REDSHIFT_ROLE_NAME        = module.redshift_analysis.aws_iam_role.redshift_role.name
#     # REDSHIFT_ROLE_ARN         = module.redshift_analysis.aws_iam_role.redshift_role.arn
#     # REDSHIFT_CLUSTER_ENDPOINT = module.aws_redshift_cluster.rsa_redshift_cluster.endpoint

#     # CUSTOMER_DQ_RULESET_NAME         = module.glue_event_based_pipeline.CUSTOMER_DQ_RULESET_NAME
#     # CUSTOMER_DQ_REQ_RUN_ID           = module.glue_event_based_pipeline.CUSTOMER_DQ_REQ_RUN_ID
#     # CUSTOMER_DQ_EVAL_RESULTS_S3_PATH = module.glue_event_based_pipeline.CUSTOMER_DQ_EVAL_RESULTS_S3_PATH
#     # 👆 add all your variables here
#   }
# }

# # Render variables to a YAML file
# resource "local_file" "all_variables_yaml" {
#   filename        = "${path.module}/terraform_variables.yaml"
#   content         = yamlencode(local.all_vars)
#   file_permission = "0644"
# }


# # Output to confirm the file has been created
# output "variables_yaml_file_path" {
#   description = "The path to the generated YAML file containing Terraform variables."
#   value       = local_file.all_variables_yaml.filename
# }
